# Generated by Django 2.2.5 on 2020-06-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_en', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promoen',
            old_name='localization_en',
            new_name='localization_ru',
        ),
    ]
