# Generated by Django 2.2.5 on 2020-07-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_en', '0002_auto_20200627_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoen',
            name='imagealtcloud',
        ),
        migrations.RemoveField(
            model_name='promoen',
            name='imgcloud',
        ),
    ]
