# Generated by Django 2.2.5 on 2020-07-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_en', '0004_auto_20200711_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagpromoen',
            name='name',
            field=models.CharField(blank=True, default='#', max_length=50, verbose_name='Название казино'),
        ),
    ]
