# Generated by Django 2.2.5 on 2020-08-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_en', '0005_tagpromoen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoen',
            name='promo',
            field=models.CharField(blank=True, default='#', max_length=10),
        ),
    ]
