# Generated by Django 2.2.5 on 2020-07-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_en', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsen',
            old_name='localization_en',
            new_name='localization_ru',
        ),
    ]
