# Generated by Django 2.2.5 on 2020-07-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_en', '0002_auto_20200705_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsen',
            name='imagealt78',
        ),
        migrations.RemoveField(
            model_name='newsen',
            name='imagealtcloud',
        ),
        migrations.RemoveField(
            model_name='newsen',
            name='img78',
        ),
        migrations.RemoveField(
            model_name='newsen',
            name='imgcloud',
        ),
        migrations.RemoveField(
            model_name='newsen',
            name='review',
        ),
        migrations.RemoveField(
            model_name='newsen',
            name='urlaff',
        ),
    ]
