# Generated by Django 2.2.5 on 2020-07-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_en', '0003_auto_20200708_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsen',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='news_en.TagNewsEn', verbose_name='Теги'),
        ),
    ]
