# Generated by Django 2.2.5 on 2020-07-23 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_en', '0005_auto_20200720_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsen',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='news_liked_en', to=settings.AUTH_USER_MODEL),
        ),
    ]
