# Generated by Django 2.2.5 on 2020-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_en',
            name='localization_en',
            field=models.CharField(blank=True, default=0, max_length=80),
        ),
    ]
