# Generated by Django 2.2.5 on 2020-01-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0002_article_en_localization_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_en',
            name='localization_en',
            field=models.CharField(blank=True, default='#', max_length=80),
        ),
    ]
