# Generated by Django 2.2.5 on 2020-01-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0003_auto_20200118_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_en',
            old_name='localization_en',
            new_name='localization_ru',
        ),
    ]
