# Generated by Django 2.2.5 on 2020-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0005_article_en_imagealt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_en',
            name='imagealtcloud',
            field=models.CharField(blank=True, default='#', max_length=80),
        ),
        migrations.AddField(
            model_name='article_en',
            name='imgcloud',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
    ]
