# Generated by Django 2.2.5 on 2020-03-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0006_auto_20200321_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_en',
            name='imagealt78',
            field=models.CharField(blank=True, default='#', max_length=80),
        ),
        migrations.AddField(
            model_name='article_en',
            name='img78',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
    ]
