# Generated by Django 2.2.5 on 2020-03-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0007_auto_20200323_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_en',
            name='localization_ru',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
    ]
