# Generated by Django 2.2.5 on 2020-04-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0008_auto_20200328_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_en',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
