# Generated by Django 2.2.5 on 2020-04-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0009_article_en_date_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_en',
            options={'ordering': ['-date_update']},
        ),
    ]
