# Generated by Django 2.2.5 on 2020-11-19 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles_en', '0011_auto_20201119_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_en',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='article_en',
            name='localization_ru',
        ),
        migrations.AlterField(
            model_name='article_en',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=70, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='article_en',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Picture'),
        ),
    ]
