# Generated by Django 2.2.5 on 2020-01-18 07:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casino_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=160)),
                ('keywords', models.CharField(max_length=80, verbose_name='Ключевые слова')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('thumbnail_600x250', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Рисунок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('template', models.CharField(default='casino/casino_index_en.html', max_length=500, verbose_name='Шаблон')),
                ('slug', models.SlugField(blank=True, default='', max_length=160, null=True, verbose_name='slug')),
                ('activate', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('text_website', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_deposit', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_withdrawal_methods', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_withdrawal_times', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_withdrawal_limit', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_restricted_countries', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_languages', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_licences', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_live_chat', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_casino_Type', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Обзор',
                'verbose_name_plural': 'Обзоры',
            },
        ),
    ]
