# Generated by Django 2.2.5 on 2020-06-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino_online_en', '0002_casino_en_imgcloudsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino_en',
            name='imgcloudsearch',
        ),
    ]
