# Generated by Django 2.2.5 on 2020-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_online_en', '0003_remove_casino_en_imgcloudsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino_en',
            name='text_casino_Type',
        ),
        migrations.AddField(
            model_name='casino_en',
            name='search_img',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
    ]
