# Generated by Django 2.2.5 on 2020-06-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_online_en', '0006_auto_20200619_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino_en',
            name='youtube_img',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='casino_en',
            name='youtube_img_alt',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
    ]
