# Generated by Django 2.2.5 on 2020-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_online_en', '0007_auto_20200621_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casino_en',
            options={'ordering': ['-date_update'], 'verbose_name': 'Обзор', 'verbose_name_plural': 'Обзоры'},
        ),
        migrations.AddField(
            model_name='casino_en',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
